### ISSUE TITLE
meta_key fieldtype should allow for meta_keys of type array and object

### ISSUE THREAD

**Issue by DancingPigeon** [growthspark/wp-advanced-search#112]
meta_key fields should allow the user to specify an object attribute or an array key to search in the case that the object isn't a simple datatype. This would allow for the situation where a meta-key value is a post-object or an array.

This would allow for cross compatibility with popular WP plugins like Advanced Custom Fields.

**Comment by bootsz** [comment]
Meta keys stored as arrays (such as with ACF) will be supported in the next version.  I haven't looked at post object types yet but it should be possible I think.

**Comment by DancingPigeon** [comment]
Fantastic to hear- if you can get post-object types in there for the next release I don't need to worry about hacking the functionality in myself :) Love the concept of the plugin, but it's a core requirement for my purposes at the moment.

**Comment by bibi-babi** [comment]
Meanwhile, you 're there, you could set the " search " for the custom field ACF google map .
because the custom field ACF releases an array of three elements : latitude longitude , address .
 and I find "text " of your system does not know how to write correctly customield with the sub element to do the research and not only the address of the other fields
